[dev]
environment = "dev"

[defaults]
environment = "dev"

  [[defaults.lab_profiles]]
  name = "m5a.xlarge"
  description = "Hello"
  image_url = "localhost"
  node = "m5a.xlarge"

  [[defaults.lab_profiles]]
  name = "m5a.large"
  description = "Hello, there"
  image_url = "localhost"
  node = "m5a.large"

  [[defaults.nodes]]
  name = "core"
  instance = ["t3a.medium"]
  group_desired_size = 1
  group_min_size = 1
  group_max_size = 1

    [defaults.nodes.labels]
    "hub.jupyter.org/node-purpose" = "core"
    "opensciencelab.local/node-type" = "core"

  [[defaults.nodes]]
  name = "sar"
  instance = ["m5a.large", "m6a.large"]
  group_desired_size = 0
  group_min_size = 0
  group_max_size = 5

    [defaults.nodes.labels]
    "hub.jupyter.org/node-purpose" = "user"
    "opensciencelab.local/node-type" = "user"