---
name: Deploy CDK
on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  push:
    paths:
      - "cluster-cdk/**"
      # Or changes to this action:
      - .github/workflows/deploy-cluster-cdk-app.yaml
    branches:
      - main
    # If matching to a tag, the action will always run regardless if there are any changes in the path
    #tags:
    #  - "v*.*.*"

jobs:
  build-and-publish-jupyterhub-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish Custom JupyterHub Image
        uses: ./build-and-publish-jupyterhub-image.yaml
        with:
          ref_name: ${{ inputs.tagname || github.ref_name }}

  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.1.2
    with:
      tagname: ${{ inputs.tagname || github.ref_name }}

  build-and-deploy-cluster:
    runs-on: ubuntu-latest
    needs:
      - setup
      - build-and-publish-jupyterhub-image
    environment: ${{ needs.setup.outputs.environment }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.1.2
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      DEPLOY_PREFIX: ${{ needs.setup.outputs.deploy_prefix }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      IS_PROD: >-
        ${{
          needs.setup.outputs.environment == 'prod' ||
          needs.setup.outputs.environment == 'stage'
        }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/deploy_cluster_stack_role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Run Cluster Testsuite
        if: >-
          ${{
            needs.setup.outputs.environment != 'prod' &&
            needs.setup.outputs.environment != 'stage'
          }}
        run: |
          make test

      - name: CDK Deploy Cluster
        run: |-
          make deploy-cluster
