---
# yamllint disable rule:line-length
name: Validate Cluster Environment
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      envOverride:
        description: "Environment override / Lab short name"
        type: environment
        default: test

  push:
    branches:
      - main

jobs:
  build-and-deploy-cluster:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envOverride }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.2.1
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      PROFILE_DEFINITIONS: ${{ vars.PROFILE_DEFINITIONS }}
      NODE_DEFINITIONS: ${{ vars.NODE_DEFINITIONS }}
      JUPYTER_HUB_IMAGE_PATH: ${{ vars.JUPYTER_HUB_IMAGE_PATH }}
      JUPYTER_HUB_IMAGE_TAG: ${{ vars.JUPYTER_HUB_IMAGE_TAG }}
      CRYPTNONO_ALERT_EMAIL: ${{ vars.CRYPTNONO_ALERT_EMAIL }}
      EXECWHACKER_CRON_IMAGE_PATH: ${{ vars.EXECWHACKER_CRON_IMAGE_PATH }}
      EXECWHACKER_CRON_IMAGE_TAG: ${{ vars.EXECWHACKER_CRON_IMAGE_TAG }}
      IS_CRYPTNONO_ENABLED: ${{ vars.IS_CRYPTNONO_ENABLED }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      UI_IAM_ROLE: ${{ vars.UI_IAM_ROLE }}
      ADMIN_USERS: ${{ vars.ADMIN_USERS }}
      PORTAL_DOMAINS: ${{ vars.PORTAL_DOMAINS }}
      LAB_SHORT_NAME: ${{ inputs.envOverride }}
      VOLUME_CRON_SCHEDULE: ${{ vars.VOLUME_CRON_SCHEDULE }}
      SNAPSHOT_WARNING_DAYS: ${{ vars.SNAPSHOT_WARNING_DAYS }}
      SNAPSHOT_GRACEPERIOD_DAYS: ${{ vars.SNAPSHOT_GRACEPERIOD_DAYS }}
      DAYS_TILL_SNAPSHOT_DELETION: ${{ vars.DAYS_TILL_SNAPSHOT_DELETION }}
      DAYS_TILL_VOLUME_DELETION: ${{ vars.DAYS_TILL_VOLUME_DELETION }}
      AZ_LETTER: ${{ vars.AZ_LETTER }}
    steps:
      - name: Log Environment
        run: |
          echo Selected Environment: ${{ inputs.envOverride }}

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Validate Environment
        run: |-
          make validate-env
