---
# yamllint disable rule:line-length
name: Deploy Cluster CDK
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      jupyterhub-image-tag:
        description: "image tag of `opensciencelab-jupyterhub` (ex. 'dp', 'v1.0.2', etc.)"
        required: false
        default: ''

      envOverride:
        description: "Environment override"
        type: environment
        default: "dev"
  push:
    branches:
      - main

    tags:
      - "v*.*.*"

jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.1.2
    with:
      tagname: ${{ inputs.tagname || github.ref_name }}

  build-and-deploy-cluster:
    runs-on: ubuntu-latest
    needs:
      - setup
    environment: ${{ inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.1.2
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      DEPLOY_PREFIX: ${{ needs.setup.outputs.deploy_prefix }}
      JUPYTER_HUB_DOCKER_TAG: ${{ github.event.inputs.jupyterhub-image-tag || needs.setup.outputs.deploy_prefix }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      UI_IAM_USER: ${{ vars.UI_IAM_USER }}
      IS_PROD: contains(fromJSON('["prod", "stage", "avo-prod", "azdwr-prod-opensarlab", "geos626"]'), inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment )
    steps:
      - name: Log Environment
        run: |
          echo IS_PROD: ${{ env.IS_PROD }}
          echo Selected Environment: ${{ inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment }}

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/deploy_cluster_stack_role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Run Cluster Testsuite
        if: contains(fromJSON('["prod", "stage", "avo-prod", "azdwr-prod-opensarlab", "geos626"]'), inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment )
        run: |
          make test

      # - name: CDK Deploy Cluster
      #   run: |-
      #     make deploy-cluster
