---
# yamllint disable rule:line-length
name: Deploy Cluster CDK
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      envOverride:
        description: "Environment override"
        type: choice
        default: ""
        options:
          - ""
          - prod
          - test
          - dev
          - avo-prod
          - azdwr-prod-opensarlab
          - geos626
  push:
    branches:
      - main
    # If matching to a tag, the action will always run regardless if there are any changes in the path
    tags:
      - "v*.*.*"

# Jobs run in parallel, steps run in sequence
# Image builds must complete before the cluster build is started.
jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.1.2
    with:
      tagname: ${{ inputs.tagname || github.ref_name }}

  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      jupyterhub: ${{ steps.filter.outputs.jupyterhub }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            jupyterhub:
              - 'images/jupyterhub/**'

  build-and-publish-jupyterhub-image:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.jupyterhub == 'true' }}
    uses: ./.github/workflows/build-and-publish-jupyterhub-image.yaml
    with:
      ref_name: ${{ inputs.tagname || github.ref_name }}

  build-and-deploy-cluster:
    runs-on: ubuntu-latest
    # Ensure that this job always runs even if the image build doesn't
    # However, don't run if the image build fails or is cancelled
    if: >-
      always() && (needs.build-and-publish-jupyterhub-image.result == 'success' || needs.build-and-publish-jupyterhub-image.result == 'skipped') && !cancelled()
    needs:
      - setup
      - build-and-publish-jupyterhub-image
    environment: ${{ inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.1.2
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      DEPLOY_PREFIX: ${{ needs.setup.outputs.deploy_prefix }}
      JUPYTER_HUB_DOCKER_TAG: ${{ needs.setup.outputs.deploy_prefix }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      UI_IAM_USER: ${{ vars.UI_IAM_USER }}
      IS_PROD: >-
        ${{
          (inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment) == 'prod' ||
          (inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment) == 'stage'
        }}
    steps:
      - name: Log Environment
        run: |
          echo Selected Environment: ${{ inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment }}

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/deploy_cluster_stack_role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Run Cluster Testsuite
        if: >-
          ${{
            (inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment) != 'prod' &&
            (inputs.envOverride != '' && inputs.envOverride || needs.setup.outputs.environment) != 'stage'
          }}
        run: |
          make test

      - name: CDK Deploy Cluster
        run: |-
          make deploy-cluster
