---
# yamllint disable rule:line-length
name: Validate Cluster Environment
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      envOverride:
        description: "Environment override / Lab short name"
        type: environment
        default: test

  push:
    branches:
      - main

jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.2.1
    with:
      tagname: ${{ inputs.tagname || github.ref_name }}

  build-and-deploy-cluster:
    runs-on: ubuntu-latest
    needs:
      - setup
    environment: ${{ inputs.envOverride || needs.setup.outputs.environment }}
    container: ghcr.io/asfopensarlab/osl-utils:v1.2.1
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
      DEPLOY_PREFIX: ${{ needs.setup.outputs.deploy_prefix }}
      PROFILE_DEFINITIONS: ${{ vars.PROFILE_DEFINITIONS }}
      NODE_DEFINITIONS: ${{ vars.NODE_DEFINITIONS }}
      JUPYTER_HUB_IMAGE_PATH: ${{ vars.JUPYTER_HUB_IMAGE_PATH }}
      JUPYTER_HUB_IMAGE_TAG: ${{ vars.JUPYTER_HUB_IMAGE_TAG }}
      EXECWHACKER_CRON_IMAGE_PATH: ${{ vars.EXECWHACKER_CRON_IMAGE_PATH }}
      EXECWHACKER_CRON_IMAGE_TAG: ${{ vars.EXECWHACKER_CRON_IMAGE_TAG }}
      IS_CRYPTNONO_ENABLED: ${{ vars.IS_CRYPTNONO_ENABLED }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      UI_IAM_USER: ${{ vars.UI_IAM_USER }}
      ADMIN_USERS: ${{ vars.ADMIN_USERS }}
      PORTAL_DOMAINS: ${{ vars.PORTAL_DOMAINS }}
      ALLOWED_LAB_PROFILES: ${{ vars.ALLOWED_LAB_PROFILES }}
      LAB_SHORT_NAME: ${{ inputs.envOverride || needs.setup.outputs.environment }}
      VOLUME_CRON_SCHEDULE: ${{ vars.VOLUME_CRON_SCHEDULE }}
      SNAPSHOT_WARNING_DAYS: ${{ vars.SNAPSHOT_WARNING_DAYS }}
      AZ_LETTER: ${{ vars.AZ_LETTER }}
    steps:
      - name: Log Environment
        run: |
          echo Selected Environment: ${{ inputs.envOverride || needs.setup.outputs.environment }}

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/deploy_cluster_stack_role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Validate Environment
        run: |-
          make validate-env
